---
title: "Overview"
---

::: {.justify}
Notes: For the code used in this chapter (DataPrep/EDA), please refer [here](https://github.com/taso5789/ds-project-portfolio/blob/main/code/1_DataPrep_EDA.ipynb). This chapter uses the data available as of September 7, 2025.
:::

# Data

::: {.justify}
- In order to address the 10 Research Questions presented in [Introduction](01_introduction.qmd) and thereby achieve the objectives of this study, the data series listed in the @tbl-sources were collected. The table shows the category, frequency, data source, and retrieval method for each variable. In the Frequency column, "D," "W," "M," and "Q" indicate daily, weekly, monthly, and quarterly, respectively. By clicking the hyperlink attached to each data source in the Source column, you can access the corresponding data source.

  - An example of a URL GET request with `SERIES_ID`, `API_KEY`, and `YYYY-MM-DD` when using the FRED API is as follows:

    - For example, if you want to retrieve the Core PCE series from January 1, 1990 onward, substitute `'PCEPILFE'` for `SERIES_ID` and `'1990-01-01'` for `YYYY-MM-DD`. For `API_KEY`, enter your own API key.
    
    ```
    https://api.stlouisfed.org/fred/series/observations?series_id=SERIES_ID&api_key=API_KEY&file_type=json&observation_start=YYYY-MM-DD
    ```
  
  - The 1-year and 5-year Expected Changes in Inflation Rates were downloaded as CSV files from the University of Michigan Surveys of Consumers website. By clicking the hyperlink attached to each variable name, the raw data can be downloaded.
  
  - Note that the COVID-19 period dummy was constructed according to the time period, which takes the value of 1 from April 2020 to March 2021 and 0 otherwise.  
    

::: 

: Data List {#tbl-sources}

| Categroy | Variable | Frequency | Source | Method of Acquisition |
|--------------------|--------------------|---------|--------|-----------------------|
| Inflation | Core PCE | M | [FRED](https://fred.stlouisfed.org/series/PCEPILFE) | API fetch |
| Unemployment | Unemployment Rate  | M | [FRED](https://fred.stlouisfed.org/series/UNRATE) | API fetch |
| Unemployment | Noncyclical Rate of Unemployment | Q | [FRED](https://fred.stlouisfed.org/series/NROU) | API fetch |
| Business Cycles and Policy Regimes | Recession Indicators | M | [FRED](https://fred.stlouisfed.org/series/USREC) | API fetch |
| Business Cycles and Policy Regimes | Zero Lower Bound dummy | M | [FRED](https://fred.stlouisfed.org/series/FEDFUNDS) | API fetch |
| Business Cycles and Policy Regimes | COVID-19 Period dummy | M | Not Available | Created |
| Demand | Real GDP | Q | [FRED](https://fred.stlouisfed.org/series/GDPC1) | API fetch |
| Demand | Real Potential GDP | Q | [FRED](https://fred.stlouisfed.org/series/GDPPOT) | API fetch |
| Demand | Industrial Production | M | [FRED](https://fred.stlouisfed.org/series/INDPRO) | API fetch |
| Demand | Retail Sales | M | [FRED](https://fred.stlouisfed.org/series/RSAFS) | API fetch |
| Supply | Crude Oil Prices | M | [FRED](https://fred.stlouisfed.org/series/MCOILWTICO) | API fetch |
| Supply | Import Price Index | M | [FRED](https://fred.stlouisfed.org/series/IR) | API fetch |
| Supply | Labor Productivity | Q | [FRED](https://fred.stlouisfed.org/series/OPHNFB) | API fetch |
| Labor Markets | Average Hourly Earnings | M | [FRED](https://fred.stlouisfed.org/series/CES0500000003) | API fetch |
| Labor Markets | Labor Force Participation Rate | M | [FRED](https://fred.stlouisfed.org/series/CIVPART) | API fetch |
| Labor Markets | Job Openings | M | [FRED](https://fred.stlouisfed.org/series/JTSJOL) | API fetch |
| Monetary Policy | Federal Funds Effective Rate | M | [FRED](https://fred.stlouisfed.org/series/FEDFUNDS) | API fetch |
| Monetary Policy | Money Suppley (M2) | M | [FRED](https://fred.stlouisfed.org/series/M2SL) | API fetch |
| Monetary Policy | Total Assets of Federal Reserve | W | [FRED](https://fred.stlouisfed.org/series/WALCL) | API fetch |
| Inflation Expectations | 5-Year Breakeven Inflation Rate | D | [FRED](https://fred.stlouisfed.org/series/T5YIE) | API fetch |
| Inflation Expectations | 10-Year Breakeven Inflation Rate | D | [FRED](https://fred.stlouisfed.org/series/T10YIE) | API fetch |
| Inflation Expectations | [1-Year Expected Changes in Inflation Rates](https://www.sca.isr.umich.edu/files/tbmpx1px5.csv) | M | [University of Michigan](https://www.sca.isr.umich.edu/tables.html) | CSV download |
| Inflation Expectations | [5-Year Expected Changes in Inflation Rates](https://www.sca.isr.umich.edu/files/tbmpx1px5.csv) | M | [University of Michigan](https://www.sca.isr.umich.edu/tables.html) | CSV download |
