project:
  type: website
  output-dir: docs
  resources:
    - images/**

website:
  title: "Data Science Project"
  site-url: "https://taso5789.github.io/ds-project-portfolio/"
  navbar:
    # collapse-below: xl 
    left:
      - text: "Introduction"
        href: 01_introduction.qmd
      - text: "DataPrep/EDA"
        href: 02_data_prep.qmd
      - text: "Model/Method"
        menu:
        - text: "Clustering"
          href: 03_clustering.qmd
        - text: "Principal Component Analysis (PCA)"
          href: 04_pca.qmd
        - text: "Naïve Bayes"
          href: 05_naive_bayes.qmd
        - text: "Decision Trees"
          href: 06_decision_trees.qmd
        - text: "Support Vector Machine (SVM)"
          href: 07_svm.qmd
        - text: "Regression"
          href: 08_regression.qmd
        - text: "Neural Network (NN)"
          href: 09_nn.qmd
      - text: "Conclusions"
        href: 10_conclusions.qmd
    right:
      - icon: github
        href: https://github.com/taso5789/ds-project-portfolio
      - icon: linkedin
        href: https://www.linkedin.com/in/taihei-sone-586102253/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



